services:
  mongo:
    image: mongo:latest
    container_name: URLShortener-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    image: vidhi0606/urlshortener-backend:latest
    container_name: URLShortener-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongo:27017/urlShortener}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret}
      - APP_URL=${APP_URL:-http://localhost:3000/}
      - NODE_ENV=production
    depends_on:
      - mongo

  frontend:
    image: vidhi0606/urlshortener-frontend:latest
    container_name: URLShortener-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:5000/}

volumes:
  mongo-data: